name: Run Scripts

on:
  workflow_dispatch:
    inputs:
      device_codename:
        description: 'Device codename'
        required: true

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run 1_build.sh
        run: |
          bash 1_build.sh ${{ inputs.device_codename }}

      - name: Run 2_push-ota.sh
        run: |
          bash 2_push-ota.sh

      - name: Run 3_cleanup.sh
        run: |
          bash 3_cleanup.sh